# Generated by Django 4.1.3 on 2022-11-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.URLField()),
                ('job', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('pantone_value', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('text', models.TextField()),
            ],
        ),
    ]
