# Generated by Django 4.1.3 on 2022-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='id_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
