# Generated by Django 4.1.3 on 2022-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0004_resource_id_ser_alter_resource_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='id_user',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
